apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: flux-system
spec:
  releaseName: mariadb
  targetNamespace: db
  chart:
    spec:
      chart: mariadb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      # version: ">=10.1.1 <10.6.0"
      # version: 15.2.2
      version: 11.0.10
  interval: 1h0m0s
  install:
    remediation:
      retries: -1
  values:
    image:
      # tag: 11.2.2-debian-11-r6
      tag: 10.6.8-debian-10-r0
    architecture: standalone
    auth:
      replicationUser: replicator
      username: maria_adm
      existingSecret: mariadb-password-secret
    diagnosticMode:
      enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        labels:
          app: mariadb
          release: kube-prometheus-stack
        jobLabel: mariadb-metrics
        enabled: false
        namespace: db
    primary:
      readinessProbe:
        enabled: false
      persistence:
        enabled: true
        existingClaim: db-mariadb-pvc